name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install test dependencies
        run: brew install bats-core

      - name: Run tests
        run: bats test/
